### ISSUE TITLE
401 Authentication Error

### ISSUE THREAD

**Issue by LukeFireproof** [UnrealByteGames/Easy-Jira#1]
I've configured my jira settings as shown in the attached image but get 401 error (no further info) when I hit refresh in the issue admin browser. All the details are correct. 
![croppercapture 153](https://user-images.githubusercontent.com/37867088/41045338-218e9eea-69a0-11e8-9199-27501c3480f4.png)

**Comment by unrealbyte** [comment]
Fixed in version 1.3.0 sent to the asset store today.
